---
title: "Spatial Mixed-Effects Modelling with spicy"
date: "`r BiocStyle::doc_date()`"
params:
  test: FALSE
author:
- name: Alexander Nicholls
  affiliation:  
  - School of Mathematics and Statistics, University of Sydney, Australia
- name: Ellis Patrick
  affiliation:
  - &WIMR Westmead Institute for Medical Research, University of Sydney, Australia
  - School of Mathematics and Statistics, University of Sydney, Australia
- name: Nicolas Canete
  affiliation:  
  - &WIMR Westmead Institute for Medical Research, University of Sydney, Australia
vignette: >
  %\VignetteIndexEntry{"Introduction to simpleSeg"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document
---
  
```{r, include = FALSE}
# knitr::opts_chunk$set(
#   collapse = TRUE,
#   comment = "#>"
# )
# library(BiocStyle)
```


```{r warning=FALSE, message=FALSE}
# # load required packages
# library(Statial)
# 
# # .libPaths("/dora/nobackup/biostat/Rpackages/v4")
# 
# library(ggplot2)
# library(spicyR)
# library(tidyverse)
# library(SingleCellExperiment)
```

# Installation

```{r, eval = FALSE}
# # Install the development version from GitHub:
# # install.packages("devtools")
# devtools::install_github("SydneyBioX/Statial")
```

# Overview

The `Statial` package provides functionality to.... 


# Load example data

In the following we will reanalyse......

```{r}
# sce = readRDS("/albona/nobackup2/biostat/datasets/spatial/Damond2019_Diabetes_IMC/analysis/DamondCellsSCE.rds")

# cellExp = readRDS("../data/cellExp.RDS")
# intensities = data.frame(t(data.frame(cellMarks(cellExp))))
# colnames(intensities) =  paste0("cellID", cellSummary(cellExp)$cellID)
# 
# spatialMeasurements = data.frame(cellSummary(cellExp))
# rownames(spatialMeasurements) = paste0("cellID", cellSummary(cellExp)$cellID)
# 
# sce = SingleCellExperiment(list(intensities = intensities),
#                            colData = spatialMeasurements)
# 

# saveRDS(sce, "../data/sce.RDS")

```


```{r}
# sce = readRDS("../data/sce.RDS")
```



```{r}
# intensitiesData = data.frame(t(assay(sce, "intensities")))
# spatialData = data.frame(colData(sce))
# markersToUse = colnames(intensitiesData)
# 
# singleCellData = cbind(spatialData[rownames(intensitiesData),], intensitiesData)
# singleCellData = singleCellData %>% 
#     mutate_at(markersToUse, function(x) ifelse(is.na(x), 0, x)) %>% 
#     mutate_if(is.factor, as.character)
```


```{r}
# singleCellDataDistances = calculateCellDistances(singleCellData, nCores = 50, Rs = c(200))
```


```{r}
# singleCellDataDistancesCounts = calculateK(singleCellDataDistances, nCores = 50, Rs = c(200))
```


```{r}
# imageModels = calculateModelsAllInteractions(singleCellData = singleCellDataDistancesCounts, 
#                                markers = markersToUse, 
#                                typeAll = c("dist"),
#                                nCores = 50)
```

```{r}
# fastImageModels = function(singleCellData,
#                            type = "dist",
#                            markers,
#                            covariates = NULL,
#                            removeColsThresh = 0.1){
# 
#     model = try({
#         singleCellData = singleCellData %>%
#             dplyr::select(imageID, cellType, starts_with(type), dplyr::all_of(markers), dplyr::all_of(covariates))
# 
#         singleCellData = na.omit(singleCellData[,colSums(is.na(singleCellData)) < removeColsThresh*nrow(singleCellData)])
# 
#         x.train.original = singleCellData %>%
#             dplyr::select(starts_with(type))
#         x.train = bigstatsr::as_FBM(x.train.original)
#         y.train = singleCellData %>%
#              dplyr::select(dplyr::all_of(markers)) %>%
#              select_if(~ length(unique(.)) > 1)
# 
#         y.train = apply(y.train, MARGIN = 2, function(x) x, simplify = FALSE)
#         cov.train = singleCellData %>%
#             dplyr::select(dplyr::all_of(covariates))
# 
#         model = mapply(FUN = function(y.train) bigstatsr::big_univLinReg(X = x.train, y.train = y.train , covar.train = as.matrix(cov.train)),
#                    y.train = y.train,
#                    SIMPLIFY = FALSE) %>%
#                 mapply(FUN = function(x, dependent) x %>% dplyr::mutate(independent = colnames(x.train.original),
#                                                                         dependent = dependent), dependent = names(.), SIMPLIFY = FALSE) %>%
#             dplyr::bind_rows()
# 
#         model = model %>%
#             dplyr::mutate(sampleSize = nrow(x.train)) %>%
#             dplyr::mutate(imageID = unique(singleCellData$imageID),
#                           cellType = unique(singleCellData$cellType),
#                           pValue = ifelse(is.na(score), NA, 2*pt(abs(score), df = sampleSize - 2 - ncol(cov.train), lower.tail = FALSE))
#                           ) %>%
#             dplyr::relocate(imageID, cellType, independent, dependent) %>%
#             dplyr::mutate(interactingCell = word(independent, 2, -1, "_"), type = word(independent, 1, 1, "_")) %>%
#             dplyr::rename(beta = "estim", tValue = "score") %>%
#             data.frame()
#     })
# 
#     model
# }

# 
# imageModels = BiocParallel::bplapply(split(singleCellDataDistancesCounts, ~imageID + cellType), 
#                            fastImageModels, 
#                            markers = markersToUse,
#                            BPPARAM = BiocParallel::MulticoreParam(workers = 50))
# 


```








```{r}
# mixedModels = calculateModelsAllInteractions(singleCellData = singleCellDataDistancesCounts, 
#                                markers = markersToUse, 
#                                typeAll = c("dist"),
#                                isMixed = TRUE,
#                                nCores = 50)
# 
# mixedModels %>% 
#     filter(pValue*nrow(.) < 0.05) %>% 
#     filter(relativeExpression < 1, relativeExpression > 0) %>% 
#     filter(cellType != "Undefined", interactingCell != "Undefined") 
# 

```


```{r}
# imageModels %>% 
#     filter(cellType == "MC2", independent == "dist200_SC7", dependent == "Podoplanin") 

```



```{r}
# visualiseImageRelationship(singleCellData, 
#                           imageID = "36", 
#                           mainCellType = "MC2",
#                           interactingCellType = "SC7",
#                           depedentMarker = "Podoplanin", 
#                           interactive = TRUE, 
#                           plotModelFit = FALSE,
#                           method = "lm",
#                           modelType = "dist200_")
```


## Cross Validation
```{r}
# crossValidationData = imageModelsCVFormat(imageModels, 
#                                           values_from = "tValue",  
#                                           removeColsThresh = 0.2, 
#                                           missingReplacement = 0)
```


## Session Info
```{r}
# sessionInfo()
```


