---
title: "Statial draft"
date: "`r BiocStyle::doc_date()`"
params:
  test: FALSE
author:
- name: Farhan Ameen
  affiliation:  
  - School of Mathematics and Statistics, University of Sydney, Australia
- name: Sourish Iyengar
  affiliation:
  - School of Mathematics and Statistics, University of Sydney, Australia
- name: Ellis Patrick
  affiliation:
  - &WIMR Westmead Institute for Medical Research, University of Sydney, Australia
  - School of Mathematics and Statistics, University of Sydney, Australia
vignette: >
  %\VignetteIndexEntry{"Statial draft"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(BiocStyle)
```




```{r warning=FALSE, message=FALSE}
# load required packages
library(Statial)
library(ggplot2)
library(spicyR)
library(tidyverse)
library(ClassifyR)
library(SingleCellExperiment)
```



```{r}
# cellExp = readRDS("Head and Neck/cellExp.RDS")
# intensities = data.frame(t(data.frame(cellMarks(cellExp))))
# colnames(intensities) =  paste0("cellID", cellSummary(cellExp)$cellID)
#
# spatialMeasurements = data.frame(cellSummary(cellExp))
# rownames(spatialMeasurements) = paste0("cellID", cellSummary(cellExp)$cellID)
#
# clinicalHeadData = imagePheno(cellExp) %>%
#   select(subject, imageID, condition)
#
#
# headSCE = SingleCellExperiment(list(intensities = intensities),
#                            colData = c(spatialMeasurements))
#
# save(headSCE, clinicalHeadData, file = "headSCE.rda")
```


```{r}
data(headSCE)
intensitiesData <- data.frame(t(assay(headSCE, "intensities")))
spatialData <- data.frame(colData(headSCE))
markersToUse <- colnames(intensitiesData)

singleCellData <- cbind(spatialData[rownames(intensitiesData), ], intensitiesData)
singleCellData <- singleCellData %>%
  mutate_at(markersToUse, function(x) ifelse(is.na(x), 0, x)) %>% #replace NAs with 0
  mutate_if(is.factor, as.character)
```

Measures distances between the two cell types mentioned?
```{r}
singleCellDataDistances <- getDistances(singleCellData,
  nCores = 1,
  Rs = c(200),
  whichCellTypes = c("MC2", "SC7")
)
```

Generates some sort of number that encodes how many cells of each type are within the radius of a cell
```{r}
singleCellDataDistancesCounts <- getAbundances(singleCellDataDistances,
  nCores = 1,
  Rs = c(200),
  whichCellTypes = c("MC2", "SC7")
)
```

Looks at correlation (+whether significant) between dist200 and abundance200 with changes in marker expression
```{r, message=FALSE}
imageModels <- getStateChanges(
  singleCellData = singleCellDataDistancesCounts,
  markers = markersToUse,
  typeAll = c("dist200", "abundance200"),
  cellTypesToModel = "MC2",
  nCores = 1
)
```

Batch effect removal with ImageID
```{r}
#TODO: boundary (singular) fit
mixedModels <- getStateChanges(
  singleCellData = singleCellDataDistancesCounts,
  markers = markersToUse,
  typeAll = c("dist"),
  method = "rlm",
  # isMixed = TRUE,
  #randomIntercepts = c("imageID"),
  cellTypesToModel = "MC2",
  nCores = 1
)

mixedModels
```


```{r, eval=FALSE}
#TODO: This is broken due to NAs.
visualiseImageRelationship(
  data = singleCellDataDistances, 
  imageID = "8", 
  mainCellType = "MC2", 
  interactingCellType = "SC7", 
  depedentMarker = "Podoplanin",
  interactive = FALSE,
  plotModelFit = FALSE,
  method = "lm",
  modelType = "dist200_"
)[[1]]

  # relationshipFormula <- paste0(
  #   depedentMarker, "~", paste0(modelType, interactingCellType) 
  # )
# Podoplanin ~ dist200_SC7
```

```{r}
modelData <- singleCellDataDistances[singleCellDataDistances$cellType == "MC2", ]
modelData

any(is.na(modelData$Podoplanin))
any(is.na(modelData$dist200_SC7))

model <- lm(formula(Podoplanin ~ dist200_SC7), modelData)


```

```{r}
data = singleCellDataDistances
imageID = "36"
mainCellType = "MC2"
interactingCellType = "SC7"
depedentMarker = "Podoplanin"
method = "lm"
modelType = "dist200_"

data <- data[data$imageID == 36, ]
data$OriginalMarker <- data[, depedentMarker, drop = TRUE]
data$fittedValues <- NA

relationshipFormula <- paste0(
  depedentMarker, "~", paste0(modelType, interactingCellType) 
)
modelData <- data[data$cellType == mainCellType, ]
model <- lm(formula(Podoplanin ~ dist200_SC7), modelData)

```

```{r}
imageModelsFast <- getStateChangesFast(
  singleCellData = singleCellDataDistancesCounts,
  markers = markersToUse,
  type = c("dist200"),
  nCores = 1
)
```


## Cross Validation
```{r, eval=FALSE}
subsetImages <- clinicalHeadData %>%
  group_by(subject) %>%
  group_modify(~ tail(.x, 1)) %>%
  ungroup() %>%
  pull(imageID)

crossValidationData <- imageModelsCVFormat(imageModelsFast,
  values_from = "tValue",
  removeColsThresh = 0.2,
  missingReplacement = 0
)

crossValidationData <- crossValidationData[crossValidationData$imageID %in% subsetImages, ]
crossValidationData <- crossValidationData %>%
  column_to_rownames("imageID")



outcome <- clinicalHeadData[rownames(crossValidationData), "condition"]
outcome <- factor(outcome)
names(outcome) <- rownames(crossValidationData)

stateChangeProgressionCV <- ClassifyR::crossValidate(
  measurements = crossValidationData,
  outcome = outcome,
  nFeatures = 10,
  selectionMethod = "t-test",
  classifier = "XGB",
  nRepeats = 10,
  nCores = 10,
  characteristicsLabel = "XGB_Model"
)

stateChangeProgressionCV %>%
  performancePlot()
```

```{r}


```




## Session Info
```{r}
sessionInfo()
```

