# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.concaveHull <- function(x, y, concavity, lengthThreshold) {
    .Call(`_Statial_concaveHullR`, x, y, concavity, lengthThreshold)
}

.neighbourSummary <- function(x, y, type, n_types, r, mode) {
    .Call(`_Statial_neighbourSummary`, x, y, type, n_types, r, mode)
}

